### ISSUE TITLE
Reorganise 'using mods' guide to present per-platform info more cohesively

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/canimod.github.io#12]
The [_using mods_](http://canimod.com/guides/using-mods) guide tries to cover all platforms at once, but the result is confusing and disorganised. For example:
* _Installing SMAPI_ has a subsection for each platform.
* ...except the 'manual install' section which uses an approach like "if Windows do X else do Y".
* Elsewhere the guide uses tables to present per-platform values.

Reorganise the guide so it presents information for each platform more cohesively.

**Comment by Pathoschild** [comment]
One possible approach:

1. Add platform selector panels to affected sections ([MSDN](https://msdn.microsoft.com/en-us/library/system.string.format(v=vs.110).aspx#Starting)-style):
   >![selector mockup](https://cloud.githubusercontent.com/assets/230581/21951723/6ef4ba78-d9d9-11e6-8f59-32738a789394.png)
2. Keep the selectors in sync (e.g. choosing 'Mac' in one section shows Mac instructions everywhere).
3. Reorganise all branching documentation into these selector panels.

**Comment by Pathoschild** [comment]
@RuyiLi created a prototype at [RuyiLi/SMAPIDocFixes](https://github.com/RuyiLi/SMAPIDocFixes) (see attached [index.html](https://github.com/Pathoschild/canimod.github.io/files/706300/index.html.zip)). Thanks!

**Comment by AndrewHows** [comment]
Events can be configured and started programmatically, as shown below. This technique is used in the base game for the wedding scene in Game1.checkForWedding().

```
Game1.currentLocation.resetForPlayerEntry();
Game1.currentLocation.currentEvent = new Event("<eventdata>", -1);
Game1.eventUp = true;
Game1.player.CanMove = false;
```

**Comment by Pathoschild** [comment]
Closing since all content has long since been migrated to the wiki.
