### ISSUE TITLE
System.badImageFormatException

### ISSUE THREAD

**Issue by Davidm16** [Pathoschild/canimod.github.io#19]
![image](https://cloud.githubusercontent.com/assets/16451684/23229759/c36d51d2-f941-11e6-9a36-3e9903765907.png)

**Comment by Pathoschild** [comment]
Hi @Davidm16. Please ask in the [SMAPI discussion thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375) for help with SMAPI. :)
