### ISSUE TITLE
Multi-license content for compatibility with the wiki

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/canimod.github.io#22]
We're moving some of the guides to a new `Modding:` namespace on the [Stardew Valley wiki](http://stardewvalleywiki.com/Stardew_Valley_Wiki), to make it easier for modders to contribute. Before we do that, we need permission from contributors since the wiki has a different license.

## Permission needed
Please indicate whether you agree with this statement:
>I agree that all my contributions to the canimod repo, which uses the [MIT license](https://github.com/Pathoschild/canimod.github.io/blob/master/LICENSE), can be dual-licensed to [Creative Commons BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/).

**Comment by Pathoschild** [comment]
If your name is on this list, we need your permission:
- [x] @JohnsonNicholas
- [x] @Kithio
- [x] @KoihimeNakamura
- [x] @Pathoschild
- [x] @rumangerst
- [x] @spacechase0
- [x] @ThommyDude
- [x] @tstaples
- [x] @UlithiumDragon
- [x] @xNeptune

If you don't agree, we'll unfortunately need to delete your contributions.

**Comment by spacechase0** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.

**Comment by catamari** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.

**Comment by rumangerst** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.

**Comment by Sakorona** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0. (this applies also to @KoihimeNakamura  since that's my computer still using the ssh key for my old account)

**Comment by ThommyDude** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.

Copy&Paste crew all the way down!

**Comment by Kithio** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.

**Comment by UlithiumDragon** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.

**Comment by xNeptune** [comment]
I agree that all my contributions to the canimod repo, which uses the MIT license, can be dual-licensed to Creative Commons BY-NC-SA 3.0.
